language: php

php:
  - 5.4

before_script:
  - echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --dev --prefer-source


script: phpunit -c phpunit.xml.dist
